# Complex Networks - 4

#### 1) Configuration Model: monte uma função que recebe como entrada um histograma dos graus dos vértices e retorna uma rede com exatamente este histograma de graus (com possíveis autoloops e multi-arestas)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Questao 1)

# Histogram to Adjancy List
def hist_to_adj(x):
    l = len(x)
    G = np.zeros((1,2))
    for i in range(l):
        node_i = x[i,0]
        degree_i = x[i,1]
        for j in range(degree_i):
            G = np.append(G,[[node_i,0]],axis = 0)
    G = np.delete(G,0,0)
    return G

# Configuration Model
def configuration_model(G):
    G = hist_to_adj(G)
    l = len(G)
    nodes = np.unique(G)
    for i in range(l):
        u = np.random.choice(nodes)
        G[i,1] = u
    return G

# Network Plot
def network_plot(G):
    df = pd.DataFrame(G, columns=['A', 'B'])
    df = df.astype(int)
    G = nx.from_pandas_dataframe(df,'A','B')
    nx.draw_random(G)
    plt.show()

In [5]:
# Exemplo
x = np.array([[1, 2], [2, 1], [3,0]])
G = configuration_model(x)
G

array([[ 1.,  2.],
       [ 1.,  1.],
       [ 2.,  2.]])

#### 2) Acrescente na função acima a opção de evitar autoloops e multi-arestas.

In [6]:
# Questao 2)

# Configuration Model No Self Loop No Multi-Edges
def configuration_model_2(G):
    G = hist_to_adj(G)
    l = len(G)
    nodes = np.unique(G)
    for i in range(l):
        node_i = G[i,0]
        index = np.argwhere(nodes == node_i)
        nodes2 = np.delete(nodes, index)
        u = np.random.choice(nodes2)
        G[i,1] = u
    return G

In [7]:
x = np.array([[1, 2], [2, 1], [3,0]])
G = configuration_model_2(x)
G

array([[ 1.,  2.],
       [ 1.,  0.],
       [ 2.,  1.]])

#### 3) Acrescente na função acima a opção de haver dois histogramas, um para os graus de entrada e outro para os graus de saída.


In [53]:
# Questão 3)

# Output Histogram to Adjancy List
def hist_to_adj_out(x):
    l = len(x)
    G = np.zeros((1,2))
    for i in range(l):
        node_i = x[i,0]
        degree_i = x[i,1]
        for j in range(degree_i):
            G = np.append(G,[[node_i,0]],axis = 0)
    G = np.delete(G,0,0)
    return G

# Input Histogram to Adjancy List
def hist_to_adj_in(x):
    l = len(x)
    G = np.zeros((1,2))
    for i in range(l):
        node_i = x[i,0]
        degree_i = x[i,1]
        for j in range(degree_i):
            G = np.append(G,[[0,node_i]],axis = 0)
    G = np.delete(G,0,0)
    return G

#Configuration Model for Directed Network
def configuration_model_directed(G1,G2):
    G1 = hist_to_adj_out(G1)
    G2 = hist_to_adj_in(G2)
    l1 = len(G1)
    l2 = len(G2)
    nodes1 = np.unique(G1)
    nodes2 = np.unique(G2)
    for i in range(l1):
        node_i = G1[i,0]
        index = np.argwhere(nodes1 == node_i)
        nodes_available1 = np.delete(nodes1, index)
        u1 = np.random.choice(nodes_available1)
        G1[i,1] = u1
    for i in range(l2):
        node_i = G2[i,1]
        index = np.argwhere(nodes2 == node_i)
        nodes_available2 = np.delete(nodes2, index)
        u2 = np.random.choice(nodes_available2)
        G2[i,0] = u2    
    G = np.append(G1,G2, axis = 0)
    return G

In [58]:
x1 = np.array([[1, 2], [2, 1], [3,0]])
x1 = np.array([[1, 2], [2, 1], [3,0]])
G = configuration_model_directed(x1,x2)
G

array([[ 1.,  2.],
       [ 1.,  0.],
       [ 2.,  0.],
       [ 0.,  1.],
       [ 2.,  1.],
       [ 0.,  2.]])